### PR TITLE
This will add !important to attributes manipulated by options

### PR DESCRIPTION
**Pull request by BosseKarat**
This PR fixes [](https://github.com/webdriverio/visual-testing/issues/195) - Options related to setting attributes to selected elements such as `hideElements, removeElements, hideAfterFirstScroll` will now also add `!important` to overcome problems with inheritance in the CSS. 

In some specific cases, elements would remain visible because of because of inheritance, such as this modal: [](https://react.semantic-ui.com/modules/modal/)

Elements should now always either be hidden och removed no matter what is specified in the CSS.

### CODE REVIEW

**Comment by wswebcreation** [comment]
Fixes https://github.com/webdriverio/visual-testing/issues/195

**Comment by BosseKarat** [comment]
To avoid any mistakes I published the PR as draft @wswebcreation. Let me know if there's anything you want me to change 😄

**Comment by wswebcreation** [comment]
Awesome, will check it tomorrow. Tnx!

**Review by wswebcreation — CHANGES_REQUESTED** [review]
@BosseKarat 

The changes look good, the reason why the pipeline fails is related to the fact that forks can't use the credentials for SauceLabs to run the UI tests. 

Just one tip regarding the pull request, if you create one please give a short description about what is fixed, why and to which issue it is related. Can you do that for this one?

When everything is done we will pay you $25,- for your contribution and you will get email confirmation about this. Thanks!

**Comment by BosseKarat** [comment]
Absolutely @wswebcreation - This is my first time contributing on github so I'm a complete noob. I'm stuck in the world of Azure so everything here is quite new to me. Please let me know if there's anything else I can do to make your life easier, e.g connecting my PR to an issue, setting a reviewer etc ... 

Regarding the money - I don't need it. You've been spoon-feeding me throughout the entire process and I can't take any credit in this. It was a great learning experience for me the though, I'll take that as pay. Donate it to the armed forces of Ukraine or buy yourself a lunch. This is an awesome tool and I'm extremely thankful that you are providing it.

**Review by wswebcreation — APPROVED** [review]
Thanks!

**Comment by wswebcreation** [comment]
@BosseKarat ,

No problem, we are here to help people that want to help the community and als help us fix stuff, so my/our pleasure to guide you. 

> Regarding the money - I don't need it. You've been spoon-feeding me throughout the entire process and I can't take any credit in this. It was a great learning experience for me the though, I'll take that as pay. Donate it to the armed forces of Ukraine or buy yourself a lunch. This is an awesome tool and I'm extremely thankful that you are providing it.

We still want to pay you, maybe you can donate it yourself (we don't have these options from our platform). It's not a problem that we, in your words, "spoon-feeded" you, you still invested time to understand what happened and came up with a solution to fix this. Hopefully, this opened the door for you to see if you can contribute (more)  in the future.

**Comment by wswebcreation** [comment]
@BosseKarat 

I saw that a lot of tests failed, and when I looked into it I learned something new. You can't set the property together with `!important`, it needs to be different like [this](https://github.com/webdriverio/visual-testing/blob/f307c685ef9a3d8cbd10c673fa7956519ba84c85/packages/webdriver-image-comparison/src/clientSideScripts/hideRemoveElements.ts#L59)

I'll also release a fix for this. Imho nothing you could have known, at least I didn't so I learned something new

**Comment by BosseKarat** [comment]
I'm sorry about that @wswebcreation - I didn't mean to cause extra work for you 😞  I'm not afraid to make mistakes as long as I learn from them but it saddens me when someone else is forced to clean out my mess. Regarding the tests; I could not see anything failing other than the tests related to path. Did I miss to run a certain suite? 

Next time when I try to fix something I will make sure to link my fork into my project to make sure that everything is working as expected. Not in the terms of "it works in my machine" but as some sort of confirmation that my code is working.

**Comment by wswebcreation** [comment]
Hi @BosseKarat 

don’t feel sorry, we all learn here. The power in learning is making mistakes and learn from them. IMHO this was not a mistake, but a case we didn’t fully understand 😅

**Pull request merged**
